# Generated by Django 5.1 on 2024-08-26 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(choices=[('Модель техники', 'Technique Model'), ('Модель двигателя', 'Engine Model'), ('Модель трансмиссии', 'Transmission Model'), ('Модель ведущего моста', 'Driven Axle Model'), ('Модель управляемого моста', 'Steered Axle Model'), ('Вид ТО', 'Maintenance Type'), ('Узел отказа', 'Failure Node'), ('Способ восстановления', 'Recovery Method')], max_length=50, verbose_name='Название справочника')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Зав. № машины')),
                ('engine_serial_number', models.CharField(max_length=255, verbose_name='Зав. № двигателя')),
                ('transmission_serial_number', models.CharField(max_length=255, verbose_name='Зав. № трансмиссии')),
                ('driven_axle_serial_number', models.CharField(max_length=255, verbose_name='Зав. № ведущего моста')),
                ('steered_axle_serial_number', models.CharField(max_length=255, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract_number', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('cargo_receiver', models.CharField(max_length=255, verbose_name='Грузополучатель')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(verbose_name='Комплетакция (доп. опции)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driven_axle_model', models.ForeignKey(limit_choices_to={'entity_name': 'Модель ведущего моста'}, on_delete=django.db.models.deletion.CASCADE, related_name='driven_axle_machines', to='silant.directory', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(limit_choices_to={'entity_name': 'Модель двигателя'}, on_delete=django.db.models.deletion.CASCADE, related_name='engine_machines', to='silant.directory', verbose_name='Модель двигателя')),
                ('steered_axle_model', models.ForeignKey(limit_choices_to={'entity_name': 'Модель управляемого моста'}, on_delete=django.db.models.deletion.CASCADE, related_name='steered_axle_machines', to='silant.directory', verbose_name='Модель управляемого моста')),
                ('technique_model', models.ForeignKey(limit_choices_to={'entity_name': 'Модель техники'}, on_delete=django.db.models.deletion.CASCADE, related_name='technique_machines', to='silant.directory', verbose_name='Модель техники')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'entity_name': 'Модель трансмиссии'}, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_machines', to='silant.directory', verbose_name='Модель трансмиссии')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=255, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='silant.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'entity_name': 'Вид ТО'}, on_delete=django.db.models.deletion.CASCADE, to='silant.directory', verbose_name='Вид ТО')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.service', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refuse', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('failure_description', models.CharField(max_length=255, verbose_name='Описание отказа')),
                ('parts_used', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.CharField(max_length=255, verbose_name='Время простоя техники')),
                ('failure_node', models.ForeignKey(limit_choices_to={'entity_name': 'Узел отказа'}, on_delete=django.db.models.deletion.CASCADE, related_name='failure_complaints', to='silant.directory', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'entity_name': 'Способ восстановления'}, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_complaints', to='silant.directory', verbose_name='Способ восстановления')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.service', verbose_name='Сервисная компания')),
            ],
        ),
    ]
