# Generated by Django 5.1 on 2024-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_complaint_options_alter_complaint_failure_node_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['id'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AddField(
            model_name='directory',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
