# Generated by Django 5.1 on 2024-11-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0005_alter_machine_equipment_alter_machine_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='failure_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='silant.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='parts_used',
            field=models.TextField(blank=True, verbose_name='Используемые запасные части'),
        ),
    ]
